<a href="https://colab.research.google.com/github/RazyAnas/MachineLearning/blob/main/Web_scraping_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup # for webscarping

In [19]:
url = 'https://books.toscrape.com/catalogue/page-1.html'
headers = {
    "User-Agent": "Mozilla/5.0",
    "Accept-Language": "en-US,en;q=0.9",
    "Referer": "https://www.google.com/"
}
webpage = requests.get(url=url, headers=headers).text

In [22]:
soup = BeautifulSoup(webpage, 'lxml') # parse html

In [74]:
soup.prettify()

'<!DOCTYPE html>\n<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->\n<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->\n<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->\n<!--[if gt IE 8]><!-->\n<html class="no-js" lang="en-us">\n <!--<![endif]-->\n <head>\n  <title>\n   All products | Books to Scrape - Sandbox\n  </title>\n  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>\n  <meta content="24th Jun 2016 09:30" name="created"/>\n  <meta content="" name="description"/>\n  <meta content="width=device-width" name="viewport"/>\n  <meta content="NOARCHIVE,NOCACHE" name="robots"/>\n  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->\n  <!--[if lt IE 9]>\n        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>\n        <![endif]-->\n  <link href="../static/oscar/favicon.ico" rel="shortcut icon"/>\n  <link href="../static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>\n  <link href="../static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>\n  <link href="../static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>\n </head>\n <body class="default" id="default">\n  <header class="header container-fluid">\n   <div class="page_inner">\n    <div class="row">\n     <div class="col-sm-8 h1">\n      <a href="../index.html">\n       Books to Scrape\n      </a>\n      <small>\n       We love being scraped!\n      </small>\n     </div>\n    </div>\n   </div>\n  </header>\n  <div class="container-fluid page">\n   <div class="page_inner">\n    <ul class="breadcrumb">\n     <li>\n      <a href="../index.html">\n       Home\n      </a>\n     </li>\n     <li class="active">\n      All products\n     </li>\n    </ul>\n    <div class="row">\n     <aside class="sidebar col-sm-4 col-md-3">\n      <div id="promotions_left">\n      </div>\n      <div class="side_categories">\n       <ul class="nav nav-list">\n        <li>\n         <a href="category/books_1/index.html">\n          Books\n         </a>\n         <ul>\n          <li>\n           <a href="category/books/travel_2/index.html">\n            Travel\n           </a>\n          </li>\n          <li>\n           <a href="category/books/mystery_3/index.html">\n            Mystery\n           </a>\n          </li>\n          <li>\n           <a href="category/books/historical-fiction_4/index.html">\n            Historical Fiction\n           </a>\n          </li>\n          <li>\n           <a href="category/books/sequential-art_5/index.html">\n            Sequential Art\n           </a>\n          </li>\n          <li>\n           <a href="category/books/classics_6/index.html">\n            Classics\n           </a>\n          </li>\n          <li>\n           <a href="category/books/philosophy_7/index.html">\n            Philosophy\n           </a>\n          </li>\n          <li>\n           <a href="category/books/romance_8/index.html">\n            Romance\n           </a>\n          </li>\n          <li>\n           <a href="category/books/womens-fiction_9/index.html">\n            Womens Fiction\n           </a>\n          </li>\n          <li>\n           <a href="category/books/fiction_10/index.html">\n            Fiction\n           </a>\n          </li>\n          <li>\n           <a href="category/books/childrens_11/index.html">\n            Childrens\n           </a>\n          </li>\n          <li>\n           <a href="category/books/religion_12/index.html">\n            Religion\n           </a>\n          </li>\n          <li>\n           <a href="category/books/nonfiction_13/index.html">\n            Nonfiction\n           </a>\n          </li>\n          <li>\n           <a href="category/books/music_14/index.html">\n            Music\n           </a>\n          </li>\n          <li>\n           <a href="category/books/default_15/index.html">\n            Default\n           </a>\n          </li>\n          <li>\n           <a href="category/books/science-fiction_16/index.html">\n            Science Fiction\n           </a>\n          </li>\n          <li>\n           <a href="category/books/sports-and-games_17/index.html">\n            Sports and Games\n           </a>\n          </li>\n          <li>\n           <a href="category/books/add-a-comment_18/index.html">\n            Add a comment\n           </a>\n          </li>\n          <li>\n           <a href="category/books/fantasy_19/index.html">\n            Fantasy\n           </a>\n          </li>\n          <li>\n           <a href="category/books/new-adult_20/index.html">\n            New Adult\n           </a>\n          </li>\n          <li>\n           <a href="category/books/young-adult_21/index.html">\n            Young Adult\n           </a>\n          </li>\n          <li>\n           <a href="category/books/science_22/index.html">\n            Science\n           </a>\n          </li>\n          <li>\n           <a href="category/books/poetry_23/index.html">\n            Poetry\n           </a>\n          </li>\n          <li>\n           <a href="category/books/paranormal_24/index.html">\n            Paranormal\n           </a>\n          </li>\n          <li>\n           <a href="category/books/art_25/index.html">\n            Art\n           </a>\n          </li>\n          <li>\n           <a href="category/books/psychology_26/index.html">\n            Psychology\n           </a>\n          </li>\n          <li>\n           <a href="category/books/autobiography_27/index.html">\n            Autobiography\n           </a>\n          </li>\n          <li>\n           <a href="category/books/parenting_28/index.html">\n            Parenting\n           </a>\n          </li>\n          <li>\n           <a href="category/books/adult-fiction_29/index.html">\n            Adult Fiction\n           </a>\n          </li>\n          <li>\n           <a href="category/books/humor_30/index.html">\n            Humor\n           </a>\n          </li>\n          <li>\n           <a href="category/books/horror_31/index.html">\n            Horror\n           </a>\n          </li>\n          <li>\n           <a href="category/books/history_32/index.html">\n            History\n           </a>\n          </li>\n          <li>\n           <a href="category/books/food-and-drink_33/index.html">\n            Food and Drink\n           </a>\n          </li>\n          <li>\n           <a href="category/books/christian-fiction_34/index.html">\n            Christian Fiction\n           </a>\n          </li>\n          <li>\n           <a href="category/books/business_35/index.html">\n            Business\n           </a>\n          </li>\n          <li>\n           <a href="category/books/biography_36/index.html">\n            Biography\n           </a>\n          </li>\n          <li>\n           <a href="category/books/thriller_37/index.html">\n            Thriller\n           </a>\n          </li>\n          <li>\n           <a href="category/books/contemporary_38/index.html">\n            Contemporary\n           </a>\n          </li>\n          <li>\n           <a href="category/books/spirituality_39/index.html">\n            Spirituality\n           </a>\n          </li>\n          <li>\n           <a href="category/books/academic_40/index.html">\n            Academic\n           </a>\n          </li>\n          <li>\n           <a href="category/books/self-help_41/index.html">\n            Self Help\n           </a>\n          </li>\n          <li>\n           <a href="category/books/historical_42/index.html">\n            Historical\n           </a>\n          </li>\n          <li>\n           <a href="category/books/christian_43/index.html">\n            Christian\n           </a>\n          </li>\n          <li>\n           <a href="category/books/suspense_44/index.html">\n            Suspense\n           </a>\n          </li>\n          <li>\n           <a href="category/books/short-stories_45/index.html">\n            Short Stories\n           </a>\n          </li>\n          <li>\n           <a href="category/books/novels_46/index.html">\n            Novels\n           </a>\n          </li>\n          <li>\n           <a href="category/books/health_47/index.html">\n            Health\n           </a>\n          </li>\n          <li>\n           <a href="category/books/politics_48/index.html">\n            Politics\n           </a>\n          </li>\n          <li>\n           <a href="category/books/cultural_49/index.html">\n            Cultural\n           </a>\n          </li>\n          <li>\n           <a href="category/books/erotica_50/index.html">\n            Erotica\n           </a>\n          </li>\n          <li>\n           <a href="category/books/crime_51/index.html">\n            Crime\n           </a>\n          </li>\n         </ul>\n        </li>\n       </ul>\n      </div>\n     </aside>\n     <div class="col-sm-8 col-md-9">\n      <div class="page-header action">\n       <h1>\n        All products\n       </h1>\n      </div>\n      <div id="messages">\n      </div>\n      <div id="promotions">\n      </div>\n      <form class="form-horizontal" method="get">\n       <div style="display:none">\n       </div>\n       <strong>\n        1000\n       </strong>\n       results - showing\n       <strong>\n        1\n       </strong>\n       to\n       <strong>\n        20\n       </strong>\n       .\n      </form>\n      <section>\n       <div class="alert alert-warning" role="alert">\n        <strong>\n         Warning!\n        </strong>\n        This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.\n       </div>\n       <div>\n        <ol class="row">\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="a-light-in-the-attic_1000/index.html">\n             <img alt="A Light in the Attic" class="thumbnail" src="../media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Three">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="a-light-in-the-attic_1000/index.html" title="A Light in the Attic">\n             A Light in the ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£51.77\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="tipping-the-velvet_999/index.html">\n             <img alt="Tipping the Velvet" class="thumbnail" src="../media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="tipping-the-velvet_999/index.html" title="Tipping the Velvet">\n             Tipping the Velvet\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£53.74\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="soumission_998/index.html">\n             <img alt="Soumission" class="thumbnail" src="../media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="soumission_998/index.html" title="Soumission">\n             Soumission\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£50.10\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="sharp-objects_997/index.html">\n             <img alt="Sharp Objects" class="thumbnail" src="../media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Four">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="sharp-objects_997/index.html" title="Sharp Objects">\n             Sharp Objects\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£47.82\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="sapiens-a-brief-history-of-humankind_996/index.html">\n             <img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="../media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Five">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">\n             Sapiens: A Brief History ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£54.23\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="the-requiem-red_995/index.html">\n             <img alt="The Requiem Red" class="thumbnail" src="../media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="the-requiem-red_995/index.html" title="The Requiem Red">\n             The Requiem Red\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£22.65\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="the-dirty-little-secrets-of-getting-your-dream-job_994/index.html">\n             <img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="../media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Four">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">\n             The Dirty Little Secrets ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£33.34\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html">\n             <img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="../media/cache/3d/54/3d54940e57e662c4dd1f3

In [32]:
for i in soup.find_all('h3'):
  print(i.text.strip()) # proper python string

A Light in the ...
Tipping the Velvet
Soumission
Sharp Objects
Sapiens: A Brief History ...
The Requiem Red
The Dirty Little Secrets ...
The Coming Woman: A ...
The Boys in the ...
The Black Maria
Starving Hearts (Triangular Trade ...
Shakespeare's Sonnets
Set Me Free
Scott Pilgrim's Precious Little ...
Rip it Up and ...
Our Band Could Be ...
Olio
Mesaerion: The Best Science ...
Libertarianism for Beginners
It's Only the Himalayas

In [47]:
for p in soup.find_all('p', class_='star-rating'):
    rating = p['class'][1]
    print(rating)

Three
One
One
Four
Five
One
Four
Three
Four
One
Two
Four
Five
Five
Five
Three
One
One
Two
Two

In [49]:
for i in soup.find_all('p', class_='price_color'):
  print(i.text.strip()[1:])

£51.77
£53.74
£50.10
£47.82
£54.23
£22.65
£33.34
£17.93
£22.60
£52.15
£13.99
£20.66
£17.46
£52.29
£35.02
£57.25
£23.88
£37.59
£51.33
£45.17

In [53]:
for i in soup.find_all('p', class_='availability'):
  og = i.text.strip()
  text = False
  if og == 'In stock':
    text = True
  print(text)

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True

In [56]:
company = soup.find_all('article', class_='product_pod')

In [57]:
len(company)

20

In [71]:
name = []
rating = []
price = []
stock = []
for i in company:
  text = False
  name.append(i.find('h3').text.strip())
  rating.append(i.find('p', class_='star-rating')['class'][1])
  price.append(i.find('p', class_='price_color').text.strip()[1:])
  og = i.find('p', class_='availability').text.strip()
  if og == 'In stock':
    text = True
  stock.append(text)

In [72]:
d = {'name':name, 'rating':rating, 'price':price, 'availability':stock}

In [73]:
pd.DataFrame(d)

                                     name rating   price  availability
0                      A Light in the ...  Three  £51.77          True
1                      Tipping the Velvet    One  £53.74          True
2                              Soumission    One  £50.10          True
3                           Sharp Objects   Four  £47.82          True
4            Sapiens: A Brief History ...   Five  £54.23          True
5                         The Requiem Red    One  £22.65          True
6            The Dirty Little Secrets ...   Four  £33.34          True
7                 The Coming Woman: A ...  Three  £17.93          True
8                     The Boys in the ...   Four  £22.60          True
9                         The Black Maria    One  £52.15          True
10  Starving Hearts (Triangular Trade ...    Two  £13.99          True
11                  Shakespeare's Sonnets   Four  £20.66          True
12                            Set Me Free   Five  £17.46          True
13    Scott Pilgrim's Precious Little ...   Five  £52.29          True
14                      Rip it Up and ...   Five  £35.02          True
15                  Our Band Could Be ...  Three  £57.25          True
16                                   Olio    One  £23.88          True
17        Mesaerion: The Best Science ...    One  £37.59          True
18           Libertarianism for Beginners    Two  £51.33          True
19                It's Only the Himalayas    Two  £45.17          True

In [81]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

final = pd.DataFrame()

for j in range(1, 51):   # pages 1 to 50
    url = f"https://books.toscrape.com/catalogue/page-{j}.html"

    headers = {
        "User-Agent": "Mozilla/5.0",
        "Accept-Language": "en-US,en;q=0.9",
        "Referer": "https://www.google.com/"
    }

    webpage = requests.get(url, headers=headers).text
    soup = BeautifulSoup(webpage, "html.parser")

    # all book cards on the page
    books = soup.find_all("article", class_="product_pod")

    # temporary lists for one page
    name = []
    rating = []
    price = []
    stock = []

    for book in books:
        # title
        name.append(book.find("h3").find("a")["title"])

        # rating (One, Two, Three, Four, Five)
        rating.append(book.find("p", class_="star-rating")["class"][1])

        # price (remove £ symbol)
        price.append(float(book.find("p", class_="price_color").text[2:]))

        # availability
        availability_text = book.find("p", class_="availability").text.strip()
        stock.append("In stock" in availability_text)

    # DataFrame for this page
    temp_df = pd.DataFrame({
        "name": name,
        "rating": rating,
        "price (£)": price,
        "availability": stock
    })

    # add to final DataFrame
    final = pd.concat([final, temp_df], ignore_index=True)

                                    name rating  price (£)  availability
0                   A Light in the Attic  Three      51.77          True
1                     Tipping the Velvet    One      53.74          True
2                             Soumission    One      50.10          True
3                          Sharp Objects   Four      47.82          True
4  Sapiens: A Brief History of Humankind   Five      54.23          True
(1000, 4)

In [82]:
final.head()

                                    name rating  price (£)  availability
0                   A Light in the Attic  Three      51.77          True
1                     Tipping the Velvet    One      53.74          True
2                             Soumission    One      50.10          True
3                          Sharp Objects   Four      47.82          True
4  Sapiens: A Brief History of Humankind   Five      54.23          True