<a href="https://colab.research.google.com/github/RazyAnas/MachineLearning/blob/main/05_Merge/Auto_MPG/Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MPG Cars

### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries

In [31]:
import pandas as pd
import numpy as np

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv).

   ### Step 3. Assign each to a variable called cars1 and cars2

In [10]:
cars1 = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv')
cars2 = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv')

### Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

In [27]:
cars1 = cars1.loc[:, ~cars1.columns.str.contains("^Unnamed")] # dynamically remove unnamed columns
cars1.head(5)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino

In [26]:
cars2.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,33.0,4,91,53,1795,17.4,76,3,honda civic
1,20.0,6,225,100,3651,17.7,76,1,dodge aspen se
2,18.0,6,250,78,3574,21.0,76,1,ford granada ghia
3,18.5,6,250,110,3645,16.2,76,1,pontiac ventura sj
4,17.5,6,258,95,3193,17.8,76,1,amc pacer d/l

### Step 5. What is the number of observations in each dataset?

In [19]:
cars1.shape
cars2.shape

(200, 9)

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [30]:
cars = cars1.merge(cars2, how='outer').reset_index(drop=True)
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,9.0,8,304,193,4732,18.5,70,1,hi 1200d
1,10.0,8,307,200,4376,15.0,70,1,chevy c20
2,10.0,8,360,215,4615,14.0,70,1,ford f250
3,11.0,8,318,210,4382,13.5,70,1,dodge d200
4,11.0,8,350,180,3664,11.0,73,1,oldsmobile omega
...,...,...,...,...,...,...,...,...,...
393,43.4,4,90,48,2335,23.7,80,2,vw dasher (diesel)
394,44.0,4,97,52,2130,24.6,82,2,vw pickup
395,44.3,4,90,48,2085,21.7,80,2,vw rabbit c (diesel)
396,44.6,4,91,67,1850,13.8,80,3,honda civic 1500 gl
397,46.6,4,86,65,2110,17.9,80,3,mazda glc

### Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [37]:
owners = pd.Series(np.random.randint(15000, 73000, size=len(cars)))
owners

0      22162
1      25128
2      50627
3      70447
4      55650
       ...
393    19855
394    72975
395    45362
396    19302
397    28848
Length: 398, dtype: int64

### Step 8. Add the column owners to cars

In [41]:
cars['owners'] = owners
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owners
0,9.0,8,304,193,4732,18.5,70,1,hi 1200d,22162
1,10.0,8,307,200,4376,15.0,70,1,chevy c20,25128
2,10.0,8,360,215,4615,14.0,70,1,ford f250,50627
3,11.0,8,318,210,4382,13.5,70,1,dodge d200,70447
4,11.0,8,350,180,3664,11.0,73,1,oldsmobile omega,55650
...,...,...,...,...,...,...,...,...,...,...
393,43.4,4,90,48,2335,23.7,80,2,vw dasher (diesel),19855
394,44.0,4,97,52,2130,24.6,82,2,vw pickup,72975
395,44.3,4,90,48,2085,21.7,80,2,vw rabbit c (diesel),45362
396,44.6,4,91,67,1850,13.8,80,3,honda civic 1500 gl,19302
397,46.6,4,86,65,2110,17.9,80,3,mazda glc,28848