<a href="https://colab.research.google.com/github/RazyAnas/MachineLearning/blob/main/01_Getting_%26_Knowing_Your_Data/Chipotle/Exercises-Solved-By-Anas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ex2 - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [4]:
data = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep='\t')

In [6]:
data.head(2)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39

In [8]:
data.size

23110

### Step 3. Assign it to a variable called chipo.

In [9]:
chipo = data

### Step 4. See the first 10 entries

In [10]:
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 5. What is the number of observations in the dataset?

In [11]:
# Solution 1
chipo.size

23110

In [14]:
# Solution 2
chipo.info()
# there are 5 columns=order_id, quantity, item_name, choice_description, item_price
chipo.order_id.size # total rows 4622

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

4622

### Step 6. What is the number of columns in the dataset?

In [15]:
5

5

### Step 7. Print the name of all the columns.

In [29]:
chipo.columns.tolist()

['order_id', 'quantity', 'item_name', 'choice_description', 'item_price']

### Step 8. How is the dataset indexed?

In [ ]:
# zero indexing

### Step 9. Which was the most-ordered item?

In [30]:
chipo.head(2)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39

In [38]:
chipo.groupby('item_name')['quantity'].sum().sort_values(ascending=False).index[0]

'Chicken Bowl'

### Step 10. For the most-ordered item, how many items were ordered?

In [45]:
chipo.groupby('item_name')['quantity'].sum().sort_values(ascending=False).values[0].item()

761

### Step 11. What was the most ordered item in the choice_description column?

In [51]:
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [53]:
chipo.groupby('choice_description').size().sort_values(ascending=False).head(1)

choice_description
[Diet Coke]    134
dtype: int64

### Step 12. How many items were orderd in total?

In [56]:
chipo['quantity'].sum()

np.int64(4972)

### Step 13. Turn the item price into a float

#### Step 13.a. Check the item price type

#### Step 13.b. Create a lambda function and change the type of item price

#### Step 13.c. Check the item price type

### Step 14. How much was the revenue for the period in the dataset?

### Step 15. How many orders were made in the period?

### Step 16. What is the average revenue amount per order?

In [ ]:
# Solution 1

In [ ]:
# Solution 2

### Step 17. How many different items are sold?